services:
  db:
    image: postgres:17.2
    environment:
      POSTGRES_USER: trainer_helper
      POSTGRES_DB: trainer_helper
      POSTGRES_PASSWORD: alpharius
    ports:
      - 5432:5432
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    ports:
      - '8080:8080'
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - ./keycloak_export:/tmp/keycloak_export
      - ./keycloak_data:/opt/keycloak/data/h2
