// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"trainer-helper/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExerciseType creates a new instance of MockExerciseType. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExerciseType(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExerciseType {
	mock := &MockExerciseType{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExerciseType is an autogenerated mock type for the ExerciseType type
type MockExerciseType struct {
	mock.Mock
}

type MockExerciseType_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExerciseType) EXPECT() *MockExerciseType_Expecter {
	return &MockExerciseType_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockExerciseType
func (_mock *MockExerciseType) Get() ([]model.ExerciseType, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.ExerciseType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.ExerciseType, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.ExerciseType); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ExerciseType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseType_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExerciseType_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockExerciseType_Expecter) Get() *MockExerciseType_Get_Call {
	return &MockExerciseType_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockExerciseType_Get_Call) Run(run func()) *MockExerciseType_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExerciseType_Get_Call) Return(exerciseTypes []model.ExerciseType, err error) *MockExerciseType_Get_Call {
	_c.Call.Return(exerciseTypes, err)
	return _c
}

func (_c *MockExerciseType_Get_Call) RunAndReturn(run func() ([]model.ExerciseType, error)) *MockExerciseType_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserId provides a mock function for the type MockExerciseType
func (_mock *MockExerciseType) GetByUserId(userId string) ([]model.ExerciseType, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserId")
	}

	var r0 []model.ExerciseType
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]model.ExerciseType, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []model.ExerciseType); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ExerciseType)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExerciseType_GetByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserId'
type MockExerciseType_GetByUserId_Call struct {
	*mock.Call
}

// GetByUserId is a helper method to define mock.On call
//   - userId
func (_e *MockExerciseType_Expecter) GetByUserId(userId interface{}) *MockExerciseType_GetByUserId_Call {
	return &MockExerciseType_GetByUserId_Call{Call: _e.mock.On("GetByUserId", userId)}
}

func (_c *MockExerciseType_GetByUserId_Call) Run(run func(userId string)) *MockExerciseType_GetByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockExerciseType_GetByUserId_Call) Return(exerciseTypes []model.ExerciseType, err error) *MockExerciseType_GetByUserId_Call {
	_c.Call.Return(exerciseTypes, err)
	return _c
}

func (_c *MockExerciseType_GetByUserId_Call) RunAndReturn(run func(userId string) ([]model.ExerciseType, error)) *MockExerciseType_GetByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockExerciseType
func (_mock *MockExerciseType) Insert(model1 *model.ExerciseType) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.ExerciseType) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExerciseType_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockExerciseType_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockExerciseType_Expecter) Insert(model1 interface{}) *MockExerciseType_Insert_Call {
	return &MockExerciseType_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockExerciseType_Insert_Call) Run(run func(model1 *model.ExerciseType)) *MockExerciseType_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.ExerciseType))
	})
	return _c
}

func (_c *MockExerciseType_Insert_Call) Return(err error) *MockExerciseType_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExerciseType_Insert_Call) RunAndReturn(run func(model1 *model.ExerciseType) error) *MockExerciseType_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockExerciseType
func (_mock *MockExerciseType) InsertMany(models *[]model.ExerciseType) error {
	ret := _mock.Called(models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]model.ExerciseType) error); ok {
		r0 = returnFunc(models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExerciseType_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockExerciseType_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - models
func (_e *MockExerciseType_Expecter) InsertMany(models interface{}) *MockExerciseType_InsertMany_Call {
	return &MockExerciseType_InsertMany_Call{Call: _e.mock.On("InsertMany", models)}
}

func (_c *MockExerciseType_InsertMany_Call) Run(run func(models *[]model.ExerciseType)) *MockExerciseType_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*[]model.ExerciseType))
	})
	return _c
}

func (_c *MockExerciseType_InsertMany_Call) Return(err error) *MockExerciseType_InsertMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExerciseType_InsertMany_Call) RunAndReturn(run func(models *[]model.ExerciseType) error) *MockExerciseType_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockExerciseType
func (_mock *MockExerciseType) Update(model1 *model.ExerciseType) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.ExerciseType) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExerciseType_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExerciseType_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockExerciseType_Expecter) Update(model1 interface{}) *MockExerciseType_Update_Call {
	return &MockExerciseType_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockExerciseType_Update_Call) Run(run func(model1 *model.ExerciseType)) *MockExerciseType_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.ExerciseType))
	})
	return _c
}

func (_c *MockExerciseType_Update_Call) Return(err error) *MockExerciseType_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExerciseType_Update_Call) RunAndReturn(run func(model1 *model.ExerciseType) error) *MockExerciseType_Update_Call {
	_c.Call.Return(run)
	return _c
}
