// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"trainer-helper/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockExercise creates a new instance of MockExercise. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExercise(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExercise {
	mock := &MockExercise{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExercise is an autogenerated mock type for the Exercise type
type MockExercise struct {
	mock.Mock
}

type MockExercise_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExercise) EXPECT() *MockExercise_Expecter {
	return &MockExercise_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockExercise
func (_mock *MockExercise) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockExercise_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockExercise_Expecter) Delete(modelId interface{}) *MockExercise_Delete_Call {
	return &MockExercise_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockExercise_Delete_Call) Run(run func(modelId int)) *MockExercise_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_Delete_Call) Return(err error) *MockExercise_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Delete_Call) RunAndReturn(run func(modelId int) error) *MockExercise_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByExercise provides a mock function for the type MockExercise
func (_mock *MockExercise) DeleteByExercise(exerciseId int) error {
	ret := _mock.Called(exerciseId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByExercise")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(exerciseId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_DeleteByExercise_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByExercise'
type MockExercise_DeleteByExercise_Call struct {
	*mock.Call
}

// DeleteByExercise is a helper method to define mock.On call
//   - exerciseId
func (_e *MockExercise_Expecter) DeleteByExercise(exerciseId interface{}) *MockExercise_DeleteByExercise_Call {
	return &MockExercise_DeleteByExercise_Call{Call: _e.mock.On("DeleteByExercise", exerciseId)}
}

func (_c *MockExercise_DeleteByExercise_Call) Run(run func(exerciseId int)) *MockExercise_DeleteByExercise_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_DeleteByExercise_Call) Return(err error) *MockExercise_DeleteByExercise_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_DeleteByExercise_Call) RunAndReturn(run func(exerciseId int) error) *MockExercise_DeleteByExercise_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByTimeslot provides a mock function for the type MockExercise
func (_mock *MockExercise) DeleteByTimeslot(timeslotId int) error {
	ret := _mock.Called(timeslotId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByTimeslot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(timeslotId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_DeleteByTimeslot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByTimeslot'
type MockExercise_DeleteByTimeslot_Call struct {
	*mock.Call
}

// DeleteByTimeslot is a helper method to define mock.On call
//   - timeslotId
func (_e *MockExercise_Expecter) DeleteByTimeslot(timeslotId interface{}) *MockExercise_DeleteByTimeslot_Call {
	return &MockExercise_DeleteByTimeslot_Call{Call: _e.mock.On("DeleteByTimeslot", timeslotId)}
}

func (_c *MockExercise_DeleteByTimeslot_Call) Run(run func(timeslotId int)) *MockExercise_DeleteByTimeslot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_DeleteByTimeslot_Call) Return(err error) *MockExercise_DeleteByTimeslot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_DeleteByTimeslot_Call) RunAndReturn(run func(timeslotId int) error) *MockExercise_DeleteByTimeslot_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockExercise
func (_mock *MockExercise) Get() ([]model.Exercise, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Exercise, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Exercise); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockExercise_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockExercise_Expecter) Get() *MockExercise_Get_Call {
	return &MockExercise_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockExercise_Get_Call) Run(run func()) *MockExercise_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockExercise_Get_Call) Return(exercises []model.Exercise, err error) *MockExercise_Get_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExercise_Get_Call) RunAndReturn(run func() ([]model.Exercise, error)) *MockExercise_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetExerciseWorkSets provides a mock function for the type MockExercise
func (_mock *MockExercise) GetExerciseWorkSets(Id int) ([]*model.Exercise, error) {
	ret := _mock.Called(Id)

	if len(ret) == 0 {
		panic("no return value specified for GetExerciseWorkSets")
	}

	var r0 []*model.Exercise
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]*model.Exercise, error)); ok {
		return returnFunc(Id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []*model.Exercise); ok {
		r0 = returnFunc(Id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Exercise)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(Id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockExercise_GetExerciseWorkSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExerciseWorkSets'
type MockExercise_GetExerciseWorkSets_Call struct {
	*mock.Call
}

// GetExerciseWorkSets is a helper method to define mock.On call
//   - Id
func (_e *MockExercise_Expecter) GetExerciseWorkSets(Id interface{}) *MockExercise_GetExerciseWorkSets_Call {
	return &MockExercise_GetExerciseWorkSets_Call{Call: _e.mock.On("GetExerciseWorkSets", Id)}
}

func (_c *MockExercise_GetExerciseWorkSets_Call) Run(run func(Id int)) *MockExercise_GetExerciseWorkSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockExercise_GetExerciseWorkSets_Call) Return(exercises []*model.Exercise, err error) *MockExercise_GetExerciseWorkSets_Call {
	_c.Call.Return(exercises, err)
	return _c
}

func (_c *MockExercise_GetExerciseWorkSets_Call) RunAndReturn(run func(Id int) ([]*model.Exercise, error)) *MockExercise_GetExerciseWorkSets_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockExercise
func (_mock *MockExercise) Insert(model1 *model.Exercise) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Exercise) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockExercise_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockExercise_Expecter) Insert(model1 interface{}) *MockExercise_Insert_Call {
	return &MockExercise_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockExercise_Insert_Call) Run(run func(model1 *model.Exercise)) *MockExercise_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Exercise))
	})
	return _c
}

func (_c *MockExercise_Insert_Call) Return(err error) *MockExercise_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Insert_Call) RunAndReturn(run func(model1 *model.Exercise) error) *MockExercise_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockExercise
func (_mock *MockExercise) InsertMany(models *[]model.Exercise) error {
	ret := _mock.Called(models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]model.Exercise) error); ok {
		r0 = returnFunc(models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockExercise_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - models
func (_e *MockExercise_Expecter) InsertMany(models interface{}) *MockExercise_InsertMany_Call {
	return &MockExercise_InsertMany_Call{Call: _e.mock.On("InsertMany", models)}
}

func (_c *MockExercise_InsertMany_Call) Run(run func(models *[]model.Exercise)) *MockExercise_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*[]model.Exercise))
	})
	return _c
}

func (_c *MockExercise_InsertMany_Call) Return(err error) *MockExercise_InsertMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_InsertMany_Call) RunAndReturn(run func(models *[]model.Exercise) error) *MockExercise_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// UndeleteMany provides a mock function for the type MockExercise
func (_mock *MockExercise) UndeleteMany(modelIds []int) error {
	ret := _mock.Called(modelIds)

	if len(ret) == 0 {
		panic("no return value specified for UndeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int) error); ok {
		r0 = returnFunc(modelIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_UndeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndeleteMany'
type MockExercise_UndeleteMany_Call struct {
	*mock.Call
}

// UndeleteMany is a helper method to define mock.On call
//   - modelIds
func (_e *MockExercise_Expecter) UndeleteMany(modelIds interface{}) *MockExercise_UndeleteMany_Call {
	return &MockExercise_UndeleteMany_Call{Call: _e.mock.On("UndeleteMany", modelIds)}
}

func (_c *MockExercise_UndeleteMany_Call) Run(run func(modelIds []int)) *MockExercise_UndeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockExercise_UndeleteMany_Call) Return(err error) *MockExercise_UndeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_UndeleteMany_Call) RunAndReturn(run func(modelIds []int) error) *MockExercise_UndeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockExercise
func (_mock *MockExercise) Update(model1 *model.Exercise) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Exercise) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExercise_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockExercise_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockExercise_Expecter) Update(model1 interface{}) *MockExercise_Update_Call {
	return &MockExercise_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockExercise_Update_Call) Run(run func(model1 *model.Exercise)) *MockExercise_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Exercise))
	})
	return _c
}

func (_c *MockExercise_Update_Call) Return(err error) *MockExercise_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExercise_Update_Call) RunAndReturn(run func(model1 *model.Exercise) error) *MockExercise_Update_Call {
	_c.Call.Return(run)
	return _c
}
