// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package store

import (
	"trainer-helper/model"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBlock creates a new instance of MockBlock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlock {
	mock := &MockBlock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlock is an autogenerated mock type for the Block type
type MockBlock struct {
	mock.Mock
}

type MockBlock_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlock) EXPECT() *MockBlock_Expecter {
	return &MockBlock_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockBlock
func (_mock *MockBlock) Delete(modelId int) error {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockBlock_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - modelId
func (_e *MockBlock_Expecter) Delete(modelId interface{}) *MockBlock_Delete_Call {
	return &MockBlock_Delete_Call{Call: _e.mock.On("Delete", modelId)}
}

func (_c *MockBlock_Delete_Call) Run(run func(modelId int)) *MockBlock_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBlock_Delete_Call) Return(err error) *MockBlock_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_Delete_Call) RunAndReturn(run func(modelId int) error) *MockBlock_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMany provides a mock function for the type MockBlock
func (_mock *MockBlock) DeleteMany(modelIds []int) error {
	ret := _mock.Called(modelIds)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int) error); ok {
		r0 = returnFunc(modelIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_DeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMany'
type MockBlock_DeleteMany_Call struct {
	*mock.Call
}

// DeleteMany is a helper method to define mock.On call
//   - modelIds
func (_e *MockBlock_Expecter) DeleteMany(modelIds interface{}) *MockBlock_DeleteMany_Call {
	return &MockBlock_DeleteMany_Call{Call: _e.mock.On("DeleteMany", modelIds)}
}

func (_c *MockBlock_DeleteMany_Call) Run(run func(modelIds []int)) *MockBlock_DeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockBlock_DeleteMany_Call) Return(err error) *MockBlock_DeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_DeleteMany_Call) RunAndReturn(run func(modelIds []int) error) *MockBlock_DeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockBlock
func (_mock *MockBlock) Get() ([]model.Block, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []model.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]model.Block, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []model.Block); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlock_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlock_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
func (_e *MockBlock_Expecter) Get() *MockBlock_Get_Call {
	return &MockBlock_Get_Call{Call: _e.mock.On("Get")}
}

func (_c *MockBlock_Get_Call) Run(run func()) *MockBlock_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlock_Get_Call) Return(blocks []model.Block, err error) *MockBlock_Get_Call {
	_c.Call.Return(blocks, err)
	return _c
}

func (_c *MockBlock_Get_Call) RunAndReturn(run func() ([]model.Block, error)) *MockBlock_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockWeeksByUserId provides a mock function for the type MockBlock
func (_mock *MockBlock) GetBlockWeeksByUserId(userId string) ([]model.Block, error) {
	ret := _mock.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockWeeksByUserId")
	}

	var r0 []model.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]model.Block, error)); ok {
		return returnFunc(userId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []model.Block); ok {
		r0 = returnFunc(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlock_GetBlockWeeksByUserId_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockWeeksByUserId'
type MockBlock_GetBlockWeeksByUserId_Call struct {
	*mock.Call
}

// GetBlockWeeksByUserId is a helper method to define mock.On call
//   - userId
func (_e *MockBlock_Expecter) GetBlockWeeksByUserId(userId interface{}) *MockBlock_GetBlockWeeksByUserId_Call {
	return &MockBlock_GetBlockWeeksByUserId_Call{Call: _e.mock.On("GetBlockWeeksByUserId", userId)}
}

func (_c *MockBlock_GetBlockWeeksByUserId_Call) Run(run func(userId string)) *MockBlock_GetBlockWeeksByUserId_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockBlock_GetBlockWeeksByUserId_Call) Return(blocks []model.Block, err error) *MockBlock_GetBlockWeeksByUserId_Call {
	_c.Call.Return(blocks, err)
	return _c
}

func (_c *MockBlock_GetBlockWeeksByUserId_Call) RunAndReturn(run func(userId string) ([]model.Block, error)) *MockBlock_GetBlockWeeksByUserId_Call {
	_c.Call.Return(run)
	return _c
}

// GetById provides a mock function for the type MockBlock
func (_mock *MockBlock) GetById(modelId int) (model.Block, error) {
	ret := _mock.Called(modelId)

	if len(ret) == 0 {
		panic("no return value specified for GetById")
	}

	var r0 model.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (model.Block, error)); ok {
		return returnFunc(modelId)
	}
	if returnFunc, ok := ret.Get(0).(func(int) model.Block); ok {
		r0 = returnFunc(modelId)
	} else {
		r0 = ret.Get(0).(model.Block)
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(modelId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlock_GetById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetById'
type MockBlock_GetById_Call struct {
	*mock.Call
}

// GetById is a helper method to define mock.On call
//   - modelId
func (_e *MockBlock_Expecter) GetById(modelId interface{}) *MockBlock_GetById_Call {
	return &MockBlock_GetById_Call{Call: _e.mock.On("GetById", modelId)}
}

func (_c *MockBlock_GetById_Call) Run(run func(modelId int)) *MockBlock_GetById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockBlock_GetById_Call) Return(model1 model.Block, err error) *MockBlock_GetById_Call {
	_c.Call.Return(model1, err)
	return _c
}

func (_c *MockBlock_GetById_Call) RunAndReturn(run func(modelId int) (model.Block, error)) *MockBlock_GetById_Call {
	_c.Call.Return(run)
	return _c
}

// Insert provides a mock function for the type MockBlock
func (_mock *MockBlock) Insert(model1 *model.Block) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Insert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Block) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_Insert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Insert'
type MockBlock_Insert_Call struct {
	*mock.Call
}

// Insert is a helper method to define mock.On call
//   - model1
func (_e *MockBlock_Expecter) Insert(model1 interface{}) *MockBlock_Insert_Call {
	return &MockBlock_Insert_Call{Call: _e.mock.On("Insert", model1)}
}

func (_c *MockBlock_Insert_Call) Run(run func(model1 *model.Block)) *MockBlock_Insert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Block))
	})
	return _c
}

func (_c *MockBlock_Insert_Call) Return(err error) *MockBlock_Insert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_Insert_Call) RunAndReturn(run func(model1 *model.Block) error) *MockBlock_Insert_Call {
	_c.Call.Return(run)
	return _c
}

// InsertMany provides a mock function for the type MockBlock
func (_mock *MockBlock) InsertMany(models *[]model.Block) error {
	ret := _mock.Called(models)

	if len(ret) == 0 {
		panic("no return value specified for InsertMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]model.Block) error); ok {
		r0 = returnFunc(models)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_InsertMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertMany'
type MockBlock_InsertMany_Call struct {
	*mock.Call
}

// InsertMany is a helper method to define mock.On call
//   - models
func (_e *MockBlock_Expecter) InsertMany(models interface{}) *MockBlock_InsertMany_Call {
	return &MockBlock_InsertMany_Call{Call: _e.mock.On("InsertMany", models)}
}

func (_c *MockBlock_InsertMany_Call) Run(run func(models *[]model.Block)) *MockBlock_InsertMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*[]model.Block))
	})
	return _c
}

func (_c *MockBlock_InsertMany_Call) Return(err error) *MockBlock_InsertMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_InsertMany_Call) RunAndReturn(run func(models *[]model.Block) error) *MockBlock_InsertMany_Call {
	_c.Call.Return(run)
	return _c
}

// UndeleteMany provides a mock function for the type MockBlock
func (_mock *MockBlock) UndeleteMany(modelIds []int) error {
	ret := _mock.Called(modelIds)

	if len(ret) == 0 {
		panic("no return value specified for UndeleteMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]int) error); ok {
		r0 = returnFunc(modelIds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_UndeleteMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UndeleteMany'
type MockBlock_UndeleteMany_Call struct {
	*mock.Call
}

// UndeleteMany is a helper method to define mock.On call
//   - modelIds
func (_e *MockBlock_Expecter) UndeleteMany(modelIds interface{}) *MockBlock_UndeleteMany_Call {
	return &MockBlock_UndeleteMany_Call{Call: _e.mock.On("UndeleteMany", modelIds)}
}

func (_c *MockBlock_UndeleteMany_Call) Run(run func(modelIds []int)) *MockBlock_UndeleteMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]int))
	})
	return _c
}

func (_c *MockBlock_UndeleteMany_Call) Return(err error) *MockBlock_UndeleteMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_UndeleteMany_Call) RunAndReturn(run func(modelIds []int) error) *MockBlock_UndeleteMany_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockBlock
func (_mock *MockBlock) Update(model1 *model.Block) error {
	ret := _mock.Called(model1)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*model.Block) error); ok {
		r0 = returnFunc(model1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBlock_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockBlock_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - model1
func (_e *MockBlock_Expecter) Update(model1 interface{}) *MockBlock_Update_Call {
	return &MockBlock_Update_Call{Call: _e.mock.On("Update", model1)}
}

func (_c *MockBlock_Update_Call) Run(run func(model1 *model.Block)) *MockBlock_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*model.Block))
	})
	return _c
}

func (_c *MockBlock_Update_Call) Return(err error) *MockBlock_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBlock_Update_Call) RunAndReturn(run func(model1 *model.Block) error) *MockBlock_Update_Call {
	_c.Call.Return(run)
	return _c
}
