DROP TABLE IF EXISTS week_day CASCADE;

DROP TABLE IF EXISTS week CASCADE;

DROP TABLE IF EXISTS block CASCADE;

DROP SEQUENCE IF EXISTS week_day_id_seq;

DROP SEQUENCE IF EXISTS week_id_seq;

DROP SEQUENCE IF EXISTS block_id_seq;

--
