name: Build and Push Go Docker Image to GitHub Container Registry

on:
  push:
    branches:
      - ci # Trigger the workflow on push to the `main` branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx (to enable multi-platform support)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/trainer-helper-backend-go/trainer-helper:latest .

      # Push the Docker image to GitHub Container Registry
      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/trainer-helper-backend-go/trainer-helper:latest 

