name: Go

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        image: postgres:17.2
        # Provide the password for postgres
        env:
          POSTGRES_USER: trainer_helper
          POSTGRES_DB: trainer_helper
          POSTGRES_PASSWORD: alpharius
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U trainer_helper; do
            echo "$(date) - waiting for database to start"
            sleep 2
          done
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod tidy && go mod download

      - name: Build
        run: go build -v ./...

      - name: Check PostgreSQL DNS Resolution
        run: nslookup postgres

      - name: Test with the Go CLI
        env:
          APP_DB_HOST: postgres
        run: go test ./...
